name: coala-gedit
description: coala extension for gedit

configuration:
  template_dir:
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: coala-gitignore.jj2
